version: "3.7"

services:
  fastapi:
    build:
      context: ./fastapi_service/app
      dockerfile: Dockerfile
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    ports:
      - "8001:8000"
    command: uvicorn --reload main:app --host 0.0.0.0
    depends_on:
      - redis_server

  worker:
    build:
      context: ./fastapi_service/celery
      dockerfile: Dockerfile
    environment:
      REDISSERVER: redis://redis_server:6379

    depends_on:
      - redis_server

  redis_server:
    image: redis

  flower:
    image: mher/flower
    command: celery --broker=redis://redis_server:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis_server